import React, { useRef } from 'react';
import { AdvancedCalculationResult } from '../lib/advancedCalculator';
import { AdvancedFormState } from '../types/advanced';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from './ui/card';
import { Button } from './ui/button';
import { Download, AlertCircle, Info, Mail, TriangleAlert } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine } from 'recharts';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { formatPlannerCurrency } from '../lib/marketContext';
import { formatPaybackMonths } from '../lib/recoveryTime';

interface Props {
  results: AdvancedCalculationResult;
  state: AdvancedFormState;
  currencyCode: string;
}

export default function AdvancedResults({ results, state, currencyCode }: Props) {
  const reportRef = useRef<HTMLDivElement>(null);
  const formatCurrency = (value: number): string => formatPlannerCurrency(value, currencyCode);
  const formatPercent = (value: number): string => `${(value * 100).toFixed(0)}%`;
  const formatSignedPercent = (value: number): string => `${value >= 0 ? '+' : ''}${(value * 100).toFixed(1)}%`;
  const debtTone = results.interestCoverageStatus === 'healthy'
    ? 'border-green-200 bg-green-50 text-vuna-primary'
    : results.interestCoverageStatus === 'watch'
      ? 'border-amber-200 bg-amber-50 text-amber-900'
      : results.interestCoverageStatus === 'risky'
        ? 'border-red-200 bg-red-50 text-red-700'
        : 'border-neutral-200 bg-neutral-50 text-vuna-slate';
  const benchmarkTone = results.benchmarkStatus === 'strong'
    ? 'border-green-200 bg-green-50 text-vuna-primary'
    : results.benchmarkStatus === 'watch'
      ? 'border-amber-200 bg-amber-50 text-amber-900'
      : results.benchmarkStatus === 'weak'
        ? 'border-red-200 bg-red-50 text-red-700'
        : 'border-neutral-200 bg-neutral-50 text-vuna-slate';
  const growthTone = results.growthRetention.status === 'funded'
    ? 'border-green-200 bg-green-50 text-vuna-primary'
    : results.growthRetention.status === 'tight'
      ? 'border-amber-200 bg-amber-50 text-amber-900'
      : results.growthRetention.status === 'shortfall'
        ? 'border-red-200 bg-red-50 text-red-700'
        : 'border-neutral-200 bg-neutral-50 text-vuna-slate';
  const sensitivityCellTone = (status: 'profit' | 'thin' | 'loss') => (
    status === 'profit'
      ? 'bg-green-50 text-vuna-primary'
      : status === 'thin'
        ? 'bg-amber-50 text-amber-900'
        : 'bg-red-50 text-red-700'
  );
  const warningGroups = [
    {
      severity: 'critical',
      title: 'Critical issues',
      icon: AlertCircle,
      className: 'border-red-200 bg-red-50 text-red-800',
      itemClassName: 'text-red-700',
    },
    {
      severity: 'warning',
      title: 'Warnings',
      icon: TriangleAlert,
      className: 'border-amber-200 bg-amber-50 text-amber-900',
      itemClassName: 'text-amber-800',
    },
    {
      severity: 'note',
      title: 'Notes',
      icon: Info,
      className: 'border-blue-100 bg-blue-50 text-blue-900',
      itemClassName: 'text-blue-800',
    },
  ] as const;

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    
    // Simple visual feedback
    const btn = document.getElementById('pdf-btn');
    if (btn) btn.innerText = 'Generating...';

    try {
      const canvas = await html2canvas(reportRef.current, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      
      // Add footer
      pdf.setFontSize(8);
      pdf.setTextColor(150);
      pdf.text(
        "Generated by Vuna Business Planner - Advanced Analysis. Not a substitute for professional financial advice. For multi-year NPV/IRR, join Expert Mode waitlist.",
        10, pdf.internal.pageSize.getHeight() - 10
      );

      pdf.save(`${state.businessName || 'Business'}_Analysis.pdf`);
    } catch (e) {
      console.error(e);
      alert('Failed to generate PDF');
    } finally {
      if (btn) btn.innerText = 'Download PDF Report';
    }
  };

  const handleEmailPDF = () => {
    alert("To email this report, please download the PDF first and attach it to your email. Automated emailing is coming soon!");
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row justify-between items-center gap-4 bg-white p-4 rounded-3xl shadow-sm border border-neutral-200">
        <h2 className="text-2xl font-bold text-vuna-dark">Your Full Analysis</h2>
        <div className="flex gap-2">
          <Button id="pdf-btn" onClick={handleDownloadPDF} className="bg-vuna-primary hover:bg-vuna-primary/90 text-white rounded-xl">
            <Download className="w-4 h-4 mr-2" /> Download PDF
          </Button>
          <Button onClick={handleEmailPDF} variant="outline" className="border-neutral-300 text-vuna-slate hover:bg-neutral-50 rounded-xl">
            <Mail className="w-4 h-4 mr-2" /> Email
          </Button>
        </div>
      </div>

      <div ref={reportRef} className="space-y-8 bg-white p-4 sm:p-8 rounded-3xl border border-neutral-200 shadow-sm">
        
        {/* Header for PDF */}
        <div className="text-center border-b border-neutral-200 pb-6 mb-6">
          <h1 className="text-3xl font-black text-vuna-dark">{state.businessName || 'Business Analysis'}</h1>
          <p className="text-vuna-slate mt-2">{new Date().toLocaleDateString()} • {state.location} • {state.industry}</p>
        </div>

        <Card className="rounded-3xl border-green-200 bg-green-50 shadow-none">
          <CardHeader>
            <CardTitle className="text-vuna-dark">Quick Summary (Simple Mode View)</CardTitle>
            <CardDescription className="text-vuna-slate">
              This panel uses the shared WACM/simple-summary engine so Advanced Mode keeps the same high-level view as Simple Mode.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div className="rounded-2xl border border-green-200 bg-white p-4">
              <p className="text-sm text-vuna-slate">Operating Break-Even</p>
              <p className="text-xl font-bold text-vuna-primary">
                {results.simpleSummary.operatingBreakEvenUnits === Infinity
                  ? 'Never'
                  : `${Math.ceil(results.simpleSummary.operatingBreakEvenUnits).toLocaleString()} units/month`}
              </p>
            </div>
            <div className="rounded-2xl border border-green-200 bg-white p-4">
              <p className="text-sm text-vuna-slate">Investment Payback</p>
              <p className="text-xl font-bold text-vuna-primary">
                {results.simpleSummary.investmentPaybackMonths === Infinity
                  ? 'Never'
                  : formatPaybackMonths(results.simpleSummary.investmentPaybackMonths)}
              </p>
            </div>
            <div className="rounded-2xl border border-green-200 bg-white p-4">
              <p className="text-sm text-vuna-slate">Monthly Profit (Simple)</p>
              <p className={`text-xl font-bold ${results.simpleSummary.monthlyProfit >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>
                {formatCurrency(results.simpleSummary.monthlyProfit)}
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Warnings */}
        {results.warnings.length > 0 && (
          <div className="space-y-3">
            {warningGroups.map((group) => {
              const groupWarnings = results.warnings.filter((warning) => warning.severity === group.severity);
              const Icon = group.icon;

              if (groupWarnings.length === 0) {
                return null;
              }

              return (
                <div key={group.severity} className={`rounded-2xl border p-4 ${group.className}`}>
                  <div className="flex items-start">
                    <Icon className="mt-0.5 mr-3 h-5 w-5 shrink-0" />
                    <div>
                      <h3 className="mb-1 text-sm font-bold uppercase tracking-wider">{group.title}</h3>
                      <ul className={`list-disc space-y-1 pl-5 text-sm ${group.itemClassName}`}>
                        {groupWarnings.map((warning) => <li key={warning.code}>{warning.message}</li>)}
                      </ul>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Executive Summary */}
        <Card className="rounded-3xl border-neutral-200 shadow-none">
          <CardHeader><CardTitle className="text-vuna-dark">Business Summary</CardTitle></CardHeader>
          <CardContent className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
              <p className="text-sm text-vuna-slate">Capital invested</p>
              <p className="text-xl font-bold text-vuna-dark">{formatCurrency(results.investedCapital)}</p>
              <p className="mt-1 text-xs leading-5 text-vuna-slate">Money tied up in equipment or the investment amount you entered.</p>
            </div>
            <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
              <p className="text-sm text-vuna-slate">Break-even Point</p>
              <p className="text-xl font-bold text-vuna-primary">
                {results.weeksToBreakEven === Infinity ? 'Never' : `${results.weeksToBreakEven.toFixed(1)} Weeks`}
              </p>
            </div>
            <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
              <p className="text-sm text-vuna-slate">Monthly Net Profit</p>
              <p className={`text-xl font-bold ${results.monthlyNetProfit >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>
                {formatCurrency(results.monthlyNetProfit)}
              </p>
            </div>
            <div className="p-4 bg-neutral-50 border border-neutral-200 rounded-2xl">
              <p className="text-sm text-vuna-slate">12-Month Net Profit</p>
              <p className={`text-xl font-bold ${results.twelveMonthNetProfit >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>
                {formatCurrency(results.twelveMonthNetProfit)}
              </p>
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 gap-8 xl:grid-cols-2">
          <Card className="rounded-3xl border-neutral-200 shadow-none">
            <CardHeader>
              <CardTitle className="text-vuna-dark">Cost Structure</CardTitle>
              <CardDescription className="text-vuna-slate">This shows how much of your monthly cost base is fixed, variable, or mixed. A higher fixed share makes the business less forgiving in bad months.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Fixed monthly cost</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.costStructure.fixedMonthlyCost)}</p>
                  <p className="mt-2 text-sm text-vuna-slate">{formatPercent(results.costStructure.fixedShare)} of your classified operating cost base</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Variable monthly cost</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.costStructure.variableMonthlyCostAtBaseSales)}</p>
                  <p className="mt-2 text-sm text-vuna-slate">{formatPercent(results.costStructure.variableShare)} of your classified operating cost base</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Mixed monthly cost</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.costStructure.mixedMonthlyCost)}</p>
                  <p className="mt-2 text-sm text-vuna-slate">{formatPercent(results.costStructure.mixedShare)} of your classified operating cost base</p>
                </div>
              </div>
              <div className="rounded-2xl border border-neutral-200 bg-white p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-vuna-slate">Effective contribution margin</p>
                <p className={`mt-2 text-2xl font-black ${results.effectiveContributionMargin >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>{formatCurrency(results.effectiveContributionMargin)}</p>
                <p className="mt-2 text-sm text-vuna-slate">
                  This is the contribution left per unit after product costs and the variable portion of operating costs are considered.
                </p>
              </div>
              <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-7 text-vuna-slate">
                {results.costStructure.riskMessage}
              </div>
            </CardContent>
          </Card>

          <Card className="rounded-3xl border-neutral-200 shadow-none">
            <CardHeader>
              <CardTitle className="text-vuna-dark">Debt Safety</CardTitle>
              <CardDescription className="text-vuna-slate">This helps show whether the business comfortably covers its loan interest or is vulnerable to a difficult month.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className={`rounded-2xl border p-5 ${debtTone}`}>
                <p className="text-xs font-semibold uppercase tracking-[0.18em]">Interest coverage</p>
                <p className="mt-2 text-3xl font-black">
                  {results.interestCoverageRatio === null ? 'N/A' : `${results.interestCoverageRatio.toFixed(2)}x`}
                </p>
                <p className="mt-3 text-sm leading-7">{results.interestCoverageMessage}</p>
              </div>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Annual interest cost</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.annualInterestCost)}</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Monthly loan payment</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.monthlyLoanPayment)}</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Monthly cash position</p>
                  <p className={`mt-2 text-xl font-bold ${results.monthlyCashPosition >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>
                    {formatCurrency(results.monthlyCashPosition)}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 gap-8 xl:grid-cols-2">
          <Card className="rounded-3xl border-neutral-200 shadow-none">
            <CardHeader>
              <CardTitle className="text-vuna-dark">Return Quality</CardTitle>
              <CardDescription className="text-vuna-slate">This compares what the business earns on capital against the benchmark hurdle rate.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className={`rounded-2xl border p-5 ${benchmarkTone}`}>
                <p className="text-xs font-semibold uppercase tracking-[0.18em]">ROIC vs benchmark</p>
                <p className="mt-2 text-3xl font-black">
                  {results.benchmarkSpread === null ? 'N/A' : formatSignedPercent(results.benchmarkSpread)}
                </p>
                <p className="mt-3 text-sm leading-7">{results.benchmarkMessage}</p>
              </div>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">ROIC</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{results.roic === null ? 'N/A' : formatPercent(results.roic)}</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Benchmark rate</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatPercent(results.benchmarkRate)}</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
                  <p className="text-sm text-vuna-slate">Invested capital</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.investedCapital)}</p>
                </div>
              </div>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div className="rounded-2xl border border-neutral-200 bg-white p-4">
                  <p className="text-sm text-vuna-slate">Reinvestment need</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.reinvestmentNeed)}</p>
                </div>
                <div className="rounded-2xl border border-neutral-200 bg-white p-4">
                  <p className="text-sm text-vuna-slate">Owner distribution</p>
                  <p className="mt-2 text-xl font-bold text-vuna-dark">{formatCurrency(results.ownerDistributionCapacity)}</p>
                </div>
              </div>
              <div className={`rounded-2xl border p-5 ${growthTone}`}>
                <p className="text-xs font-semibold uppercase tracking-[0.18em]">Growth retention plan</p>
                <p className="mt-2 text-2xl font-black">
                  {results.growthRetention.targetGrowthPercent > 0 ? `${results.growthRetention.targetGrowthPercent}% target` : 'No growth target'}
                </p>
                <p className="mt-3 text-sm leading-7">{results.growthRetention.message}</p>
                <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">
                  <div className="rounded-2xl border border-white/70 bg-white/70 p-4">
                    <p className="text-sm">Estimated growth reinvestment</p>
                    <p className="mt-2 text-lg font-bold">{formatCurrency(results.growthRetention.estimatedGrowthReinvestment)}</p>
                  </div>
                  <div className="rounded-2xl border border-white/70 bg-white/70 p-4">
                    <p className="text-sm">Recommended retention</p>
                    <p className="mt-2 text-lg font-bold">{formatCurrency(results.growthRetention.recommendedRetention)}</p>
                  </div>
                  <div className="rounded-2xl border border-white/70 bg-white/70 p-4">
                    <p className="text-sm">Cash-safe take-home</p>
                    <p className="mt-2 text-lg font-bold">{formatCurrency(results.growthRetention.cashSafeTakeHome)}</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="rounded-3xl border-neutral-200 shadow-none">
            <CardHeader>
              <CardTitle className="text-vuna-dark">Profit to Cash Bridge</CardTitle>
              <CardDescription className="text-vuna-slate">This shows why accounting profit and actual monthly cash can move differently.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                  <tbody className="divide-y divide-neutral-200">
                    <tr>
                      <td className="px-4 py-3 font-medium text-vuna-dark">Net profit</td>
                      <td className="px-4 py-3 text-right text-vuna-dark">{formatCurrency(results.cashBridge.netProfit)}</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-3 font-medium text-vuna-dark">Add back depreciation</td>
                      <td className="px-4 py-3 text-right text-vuna-primary">+{formatCurrency(results.cashBridge.depreciationAddBack)}</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-3 font-medium text-vuna-dark">Cash from operations</td>
                      <td className="px-4 py-3 text-right text-vuna-dark">{formatCurrency(results.cashBridge.cashFromOperations)}</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-3 font-medium text-vuna-dark">Less principal repayment</td>
                      <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.cashBridge.principalRepayment)}</td>
                    </tr>
                    <tr className="bg-vuna-primary/10 font-black text-lg">
                      <td className="px-4 py-4 text-vuna-dark rounded-bl-xl">Monthly cash position</td>
                      <td className={`px-4 py-4 text-right rounded-br-xl ${results.cashBridge.cashPosition >= 0 ? 'text-vuna-primary' : 'text-red-600'}`}>
                        {formatCurrency(results.cashBridge.cashPosition)}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-7 text-vuna-slate">
                {results.cashBridge.message}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Timeline Chart */}
        <Card className="rounded-3xl border-neutral-200 shadow-none">
          <CardHeader>
            <CardTitle className="text-vuna-dark">52-Week Financial Projection</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[400px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={results.timelineData} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                  <CartesianGrid strokeDasharray="3 3" opacity={0.5} />
                  <XAxis dataKey="week" label={{ value: 'Weeks', position: 'insideBottom', offset: -10 }} />
                  <YAxis tickFormatter={(val) => `${(val/1000000).toFixed(1)}M`} />
                  <Tooltip formatter={(value: number) => formatCurrency(value)} />
                  <Legend verticalAlign="top" height={36}/>
                  <Line type="monotone" dataKey="revenue" name="Cumulative Revenue" stroke="#1DB954" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="costs" name="Cumulative Costs" stroke="#ef4444" strokeWidth={2} dot={false} />
                  <Line type="monotone" dataKey="netCash" name="Net Cash Position" stroke="#1A7A3C" strokeWidth={3} dot={false} />
                  
                  {results.weeksToBreakEven > 0 && results.weeksToBreakEven <= 52 && (
                    <ReferenceLine x={Math.round(results.weeksToBreakEven)} stroke="#1A7A3C" strokeDasharray="3 3" label={{ position: 'top', value: 'Break-even' }} />
                  )}
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Three Scenarios */}
        <Card className="rounded-3xl border-neutral-200 shadow-none">
          <CardHeader><CardTitle className="text-vuna-dark">Sales Scenarios</CardTitle></CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="bg-neutral-100 text-vuna-dark">
                  <tr>
                    <th className="px-4 py-3 rounded-tl-xl">Scenario</th>
                    <th className="px-4 py-3">Sales Volume</th>
                    <th className="px-4 py-3">Break-even (Weeks)</th>
                    <th className="px-4 py-3 rounded-tr-xl">Monthly Net Profit</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-200">
                  <tr>
                    <td className="px-4 py-3 font-medium text-red-600">Low Sales (-20%)</td>
                    <td className="px-4 py-3 text-vuna-slate">{Math.round(state.unitsPerWeek * 0.8 * 4.33)} /mo</td>
                    <td className="px-4 py-3 text-vuna-slate">{results.scenarios.pessimistic.breakEvenWeeks === Infinity ? 'Never' : results.scenarios.pessimistic.breakEvenWeeks.toFixed(1)}</td>
                    <td className="px-4 py-3 text-vuna-slate">{formatCurrency(results.scenarios.pessimistic.monthlyNetProfit)}</td>
                  </tr>
                  <tr className="bg-vuna-primary/5">
                    <td className="px-4 py-3 font-bold text-vuna-dark">Expected Sales</td>
                    <td className="px-4 py-3 text-vuna-dark">{Math.round(state.unitsPerWeek * 4.33)} /mo</td>
                    <td className="px-4 py-3 text-vuna-dark">{results.scenarios.base.breakEvenWeeks === Infinity ? 'Never' : results.scenarios.base.breakEvenWeeks.toFixed(1)}</td>
                    <td className="px-4 py-3 font-bold text-vuna-dark">{formatCurrency(results.scenarios.base.monthlyNetProfit)}</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-medium text-vuna-primary">High Sales (+20%)</td>
                    <td className="px-4 py-3 text-vuna-slate">{Math.round(state.unitsPerWeek * 1.2 * 4.33)} /mo</td>
                    <td className="px-4 py-3 text-vuna-slate">{results.scenarios.optimistic.breakEvenWeeks === Infinity ? 'Never' : results.scenarios.optimistic.breakEvenWeeks.toFixed(1)}</td>
                    <td className="px-4 py-3 text-vuna-slate">{formatCurrency(results.scenarios.optimistic.monthlyNetProfit)}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-3xl border-neutral-200 shadow-none">
          <CardHeader>
            <CardTitle className="text-vuna-dark">Sensitivity Table</CardTitle>
            <CardDescription className="text-vuna-slate">This shows what happens to monthly net profit when sales move and when the cost base gets more expensive.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="bg-neutral-100 text-vuna-dark">
                  <tr>
                    <th className="px-4 py-3 rounded-tl-xl">Cost assumption</th>
                    <th className="px-4 py-3">Revenue -20%</th>
                    <th className="px-4 py-3">Revenue as planned</th>
                    <th className="px-4 py-3 rounded-tr-xl">Revenue +20%</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-200">
                  {[1, 1.15].map((costMultiplier) => {
                    const rowCells = [0.8, 1, 1.2].map((revenueMultiplier) => (
                      results.sensitivityMatrix.cells.find((cell) => cell.costMultiplier === costMultiplier && cell.revenueMultiplier === revenueMultiplier)
                    ));
                    return (
                      <tr key={costMultiplier}>
                        <td className="px-4 py-3 font-medium text-vuna-dark">
                          {costMultiplier === 1 ? 'Costs as planned' : 'Costs +15%'}
                        </td>
                        {rowCells.map((cell, index) => (
                          <td key={`${costMultiplier}-${index}`} className={`px-4 py-3 font-semibold ${cell ? sensitivityCellTone(cell.status) : 'text-vuna-slate'}`}>
                            {cell ? formatCurrency(cell.monthlyNetProfit) : 'N/A'}
                          </td>
                        ))}
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
            <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-7 text-vuna-slate">
              {results.sensitivityMatrix.summary}
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Depreciation Schedule */}
          {results.depreciationSchedule.length > 0 && (
            <Card className="rounded-3xl border-neutral-200 shadow-none">
              <CardHeader><CardTitle className="text-vuna-dark">Depreciation Schedule</CardTitle></CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-neutral-100 text-vuna-dark">
                      <tr>
                        <th className="px-4 py-2 rounded-tl-xl">Year</th>
                        <th className="px-4 py-2">Depreciation</th>
                        <th className="px-4 py-2 rounded-tr-xl">Book Value</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-neutral-200">
                      {results.depreciationSchedule.map((row) => (
                        <tr key={row.year}>
                          <td className="px-4 py-2 text-vuna-slate">{row.year}</td>
                          <td className="px-4 py-2 text-vuna-slate">{formatCurrency(row.depreciation)}</td>
                          <td className="px-4 py-2 text-vuna-slate">{formatCurrency(row.bookValue)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Loan Schedule */}
          {results.loanSchedule.length > 0 && (
            <Card className="rounded-3xl border-neutral-200 shadow-none">
              <CardHeader><CardTitle className="text-vuna-dark">Loan Repayment Schedule</CardTitle></CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-neutral-100 text-vuna-dark">
                      <tr>
                        <th className="px-4 py-2 rounded-tl-xl">Month</th>
                        <th className="px-4 py-2">Payment</th>
                        <th className="px-4 py-2">Interest</th>
                        <th className="px-4 py-2 rounded-tr-xl">Balance</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-neutral-200">
                      {results.loanSchedule.slice(0, 12).map((row) => (
                        <tr key={row.month}>
                          <td className="px-4 py-2 text-vuna-slate">{row.month}</td>
                          <td className="px-4 py-2 text-vuna-slate">{formatCurrency(row.payment)}</td>
                          <td className="px-4 py-2 text-vuna-slate">{formatCurrency(row.interest)}</td>
                          <td className="px-4 py-2 text-vuna-slate">{formatCurrency(row.balance)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Monthly P&L Summary */}
        <Card className="rounded-3xl border-neutral-200 shadow-none">
          <CardHeader>
            <CardTitle className="text-vuna-dark">Monthly Profit Breakdown</CardTitle>
            <CardDescription className="text-vuna-slate">Assumes constant sales and costs.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <tbody className="divide-y divide-neutral-200">
                  <tr><td className="px-4 py-3 font-medium text-vuna-dark">Revenue</td><td className="px-4 py-3 text-right text-vuna-slate">{formatCurrency(results.monthlyRevenue)}</td></tr>
                  <tr><td className="px-4 py-3 font-medium text-vuna-dark">Variable Costs</td><td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.monthlyVariableCosts)}</td></tr>
                  <tr><td className="px-4 py-3 font-medium text-vuna-dark">Fixed Operating Costs</td><td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.monthlyFixedOps)}</td></tr>
                  <tr><td className="px-4 py-3 font-medium text-vuna-dark">Depreciation</td><td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.monthlyDepreciation)}</td></tr>
                  {results.loanInterestThisMonth > 0 && (
                    <tr><td className="px-4 py-3 font-medium text-vuna-dark">Loan Interest (Month 1)</td><td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.loanInterestThisMonth)}</td></tr>
                  )}
                  <tr className="bg-neutral-50 font-bold"><td className="px-4 py-3 text-vuna-dark">Profit Before Tax</td><td className="px-4 py-3 text-right text-vuna-dark">{formatCurrency(results.monthlyProfitBeforeTax)}</td></tr>
                  <tr><td className="px-4 py-3 font-medium text-vuna-dark">Tax ({state.taxRate}%)</td><td className="px-4 py-3 text-right text-red-600">-{formatCurrency(results.monthlyTax)}</td></tr>
                  <tr className="bg-vuna-primary/10 font-black text-lg"><td className="px-4 py-4 text-vuna-dark rounded-bl-xl">Net Profit</td><td className="px-4 py-4 text-right text-vuna-primary rounded-br-xl">{formatCurrency(results.monthlyNetProfit)}</td></tr>
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

      </div>
    </div>
  );
}
